### PR TITLE
Fix: function forwarding now respects target_arch

### LINKED ISSUE #1: `target_arch` usage in macros is useless
[Responsible Line](https://github.com/WarrenHood/proxygen/blob/main/proxygen-macros/src/lib.rs#L109)

Hiya, trying to cross-compile from linux here. Macros (stupidly) only run on your host. This means `target_arch` == `host_arch`.
Quick fix would be having the `cfg!` be emitted in the token stream. I'll probably do a PR for this in a bit.

### PR DESCRIPTION
**Pull request by RinLovesYou**
Fixes #1 
Had to also alter the code of x86 a bit for it to work. Was able to observe all functions exported in both x86 and x86_64 dlls.

### CODE REVIEW

**Comment by WarrenHood** [comment]
Thanks! There are also a few other macros besides just the forward macro that check the target arch. Would you like to fix those in this PR? Or are you just using the forward macro?

**Comment by RinLovesYou** [comment]
The one i did see was x64 only either way, so i figured it's okay to let that fail on x86. Personally I was not using any other ones. I'll gladly take a look though

**Comment by WarrenHood** [comment]
@RinLovesYou Yeah other than the forward macro, I'm happy to merge this if you aren't using the pre hook, then I'll look at testing/fixing the pre hook later

**Comment by RinLovesYou** [comment]
That would be nice, thanks!

**Pull request merged**
